name: first_open_slideshow
description: Display a slideshow on first open
version: 0.0.4
homepage: https://github.com/felixwortmann/first_open_slideshow

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_splash_screen: ^3.0.0
  shared_preferences: ^0.5.6+2
  animations: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/flare/
    - assets/flare/send_success.flr
